name: LeetCode Sync

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode Sync
        uses: Shujianyang/leetcode-sync@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          config: |
            {
              "leetcode": {
                "username": "saagarnkashyap",
                "cookie": "${{ secrets.LEETCODE_COOKIE }}"
              },
              "github": {
                "token": "${{ secrets.GH_TOKEN }}",
                "repository": "${{ github.repository }}"
              },
              "frequency": "hourly",
              "languages": ["python3", "cpp"]
            }
